devd(8): Add -Wno-unused-local-typedefs to CFLAGS for now.
The issue is that with -Wunused-local-typedefs, our GCC 5.0 warns about
unused local typedefs in its own headers, in this case stl_algo.h which
comes in via <algorithm>, which devd(8) includes.

Example:

c++ [...] -Werror -Wall [...] -c devd.cc
In file included from /usr/include/c++/5.0/bits/stl_algo.h:61:0,
                 from /usr/include/c++/5.0/algorithm:62,
                 from devd.cc:93:
/usr/include/c++/5.0/bits/stl_heap.h: In function 'void std::pop_heap(_RAIter, _RAIter)':
/usr/include/c++/5.0/bits/stl_heap.h:266:2: error: typedef '_ValueType' locally defined but not used [-Werror=unused-local-typedefs]
  _ValueType;
  ^
[...]

More typedefs are warned about, _InputValueType, _OutputValueType, and
_DistanceType.