sys/vfs/hammer2: Remove unused local variables in hammer2_primary_xops_thread()
pmp was unused since 21a904588eeea78c4050292c4c477f008a38784f in 2015.
last_desc was never used since first appeared.

These get warned on other platform.
error: variable 'pmp' set but not used [-Werror,-Wunused-but-set-variable]
error: variable 'last_desc' set but not used [-Werror,-Wunused-but-set-variable]