sys/sys: Remove VFS_MPLOCK2 macro
- Not only vfs and filesystems are NOT using this macro,
  but also this macro doesn't work given that

- The local variable 'xlock_mpsafe' (which is visibly hidden
  from vfs C code) is being used without initializing, while
  this header doesn't provide a macro to initialze it.
  (even if it did provide the purpose of VFS_MPLOCK2 isn't
  very clear either).

- VFS_MPLOCK1 is the only one that works as expected and all
  the syscalls actually use this. Replacing VFS_MPLOCK1 with
  VFS_MPLOCK2 results compile error with -Werror=uninitialized.

  error: 'xlock_mpsafe' is used uninitialized in this function
  [-Werror=uninitialized]
      if (xlock_mpsafe) {