sys/vfs/hammer2: Avoid unused warning when !INVARIANTS
Use xchain local variable.
error: variable 'xchain' set but not used [-Werror,-Wunused-but-set-variable]