sys/vfs/hammer2: Remove unused pmp local variable
Never used since first appeared in
b7add6753e221920947c96fab3314c39a2f67fe4 in 2015.

Warned on other platform.
error: variable 'pmp' set but not used [-Werror,-Wunused-but-set-variable]