sh (1): Remove -Werror conditionally due to seven clobber candidates
GCC 5.0 is screaming about sh potentially getting clobbered by longjmp.
I don't know how to fix this and the WARNS system doesn't cover
-Wclobbered so I'm turning -Werror off forcibly until somebody else can
fix it.  The error messages are:

/usr/src/bin/sh/eval.c: In function 'exphere':
/usr/src/bin/sh/eval.c:496:6: warning: variable 'need_longjmp' might be
  clobbered by 'longjmp' or 'vfork' [-Wclobbered]
/usr/src/bin/sh/eval.c: In function 'evalcommand':
/usr/src/bin/sh/eval.c:794:6: warning: variable 'mode' might be clobbered
  by 'lngjmp' or 'vfork' [-Wclobbered]
/usr/src/bin/sh/eval.c:799:17: warning: variable 'savehandler' might be
  clobberd by 'longjmp' or 'vfork' [-Wclobbered]
/usr/src/bin/sh/histedit.c: In function 'histcmd':
/usr/src/bin/sh/histedit.c:192:8: error: variable 'pat' might be
  clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
/usr/src/bin/sh/histedit.c:198:8: error: variable 'efp' might be
  clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
/usr/src/bin/sh/parser.c: In function 'parsebackq':
/usr/src/bin/sh/parser.c:982:6: warning: variable 'saveprompt' might be
  clobbered by 'longjmp' or 'vfork' [-Wclobbered]
/usr/src/bin/sh/parser.c:973:18: warning: argument 'out' might be
  clobbered by longjmp' or 'vfork' [-Wclobbered]