gcc120: Revert the '++' to 'xx' renaming hack
This hack [1] was introduced to work around the bug with bintuils AR/MRI
script that prevented using the '+' character in filenames.  That bug
has been fixed in upstream between binutils 2.38 and 2.39 and has been
backported to our in-base bintuils 2.34 and 2.27 [2][3].  So this
renaming hack is no longer needed.

However, a new problem appeared with libstdc++/product: mkdep(1) would
fail for the 'gnu11' file group with error:
```
.../gnu/lib/gcc120/libstdc++/product/../../../../../contrib/gcc-12/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc:25:10: fatal error: gstdint.h: No such file or directory
   25 | #include "gstdint.h"
      |          ^~~~~~~~~~~
```

This problem didn't happen before because the source file
`compatibility-atomic-c++0x.cc` was copied and renamed to
`compatibility-atomic-cxx0x.cc` in ${.OBJDIR}, which was the same
directory as the generated `gstdint.h`.

Fix the problem by adding `-I${.OBJDIR}` to ${gnu11_FLAGS}.

[1] Fix static archive libstdc++.a for gcc 5.0
    commit a4ea91a4db69a4eb6e98252ee481b866c15f1b3f
[2] vendor/BINUTILS234: Accept character '+' in filename for AR/MRI scripts
    commit 56ff23fea0c25c0330858e61cc51410c03f684b2
[3] vendor/BINUTILS227: Accept character '+' in filename for AR/MRI scripts
    commit 758b211fbc0086aa3e91c4c8d628d1b128572077