sys/vfs/hammer2: Remove unused local variable bigread
Warned on other platform.
error: variable 'bigread' set but not used [-Werror,-Wunused-but-set-variable]