libtcplay: Include rijndael-alg-fst.c to fix the static library
The static library (libtcplay.a) is used by sbin/cryptdisks, which is
built as a static binary.  The missing source of 'rijndael-alg-fst.c' caused
sbin/cryptdisks to fail the linking with the following error:

    /usr/obj/srv/jenkins/workspace/DragonFlyBSD/ctools_x86_64_x86_64/usr/libexec/binutils234/elf/ld.bfd: /usr/obj/srv/jenkins/workspace/DragonFlyBSD/world_x86_64/usr/lib/libtcplay.a(rijndael-api.o): in function `rijndael_set_key':
    rijndael-api.c:(.text+0x12): undefined reference to `rijndaelKeySetupEnc'
    /usr/obj/srv/jenkins/workspace/DragonFlyBSD/ctools_x86_64_x86_64/usr/libexec/binutils234/elf/ld.bfd: rijndael-api.c:(.text+0x27): undefined reference to `rijndaelKeySetupDec'
    /usr/obj/srv/jenkins/workspace/DragonFlyBSD/ctools_x86_64_x86_64/usr/libexec/binutils234/elf/ld.bfd: /usr/obj/srv/jenkins/workspace/DragonFlyBSD/world_x86_64/usr/lib/libtcplay.a(rijndael-api.o): in function `rijndael_decrypt':
    rijndael-api.c:(.text+0x48): undefined reference to `rijndaelDecrypt'
    /usr/obj/srv/jenkins/workspace/DragonFlyBSD/ctools_x86_64_x86_64/usr/libexec/binutils234/elf/ld.bfd: /usr/obj/srv/jenkins/workspace/DragonFlyBSD/world_x86_64/usr/lib/libtcplay.a(rijndael-api.o): in function `rijndael_encrypt':
    rijndael-api.c:(.text+0x66): undefined reference to `rijndaelEncrypt'
    collect2: error: ld returned 1 exit status

Add 'rijndael-alg-fst.c' to SRCS to fix it.  Actually, this source is
also listed in sys/crypto/Makefile for rijndael.