Restore build parallelism
The build parallelism was accidently disabled with recent commits.
First, relocate libobjc headers for gcc44 to /usr/libdata/gcc44/objc
and then remove all the strict ordering to maximize build parallelism.

Exception: the gcc47 library set requires libsupc++ to be built after
libstdc++ because they share object files built by libstdc++.