sys/vfs/hammer2: Remove unused local pmp variable
Warned on other platform.
error: variable 'pmp' set but not used [-Werror,-Wunused-but-set-variable]