sys/vfs/hammer: Add missing header include
- #include <sys/param.h> to avoid following error. This happens when
  hammer_ioctl.h is included without including other hammer headers.

  /usr/include/vfs/hammer/hammer_ioctl.h:351:21: error: 'MAXPATHLEN'
  undeclared here (not in a function)