sys/vfs/hammer2: Remove unused pmp local variable
Never used since first appeared in
c92abd0f77ba75e840c762f6ac141f120ccb38dd in 2016.

Warned on other platform.
error: variable 'pmp' set but not used [-Werror,-Wunused-but-set-variable]