usb4bsd: Fix compilation with -flto.
usbd_lookup_id_by_uaa() takes const so use const in declaration.
Using -flto caused lto_wrapper to complain about:
error: uftdi_devs causes a section type conflict with urio_devs (TBI).